title: Test blog
description: This is a description
theme: jekyll-theme-hacker
author:
  name: "SomeHacker"
  email: "someone@somewebsite.somedomain"
  url: "https://ashishchaudhary.in/hacker-blog"
GITHUB_REPO: mingpepe
